function [M,B,G,W,dW,E] = Mat(q1,j1,j2,dq1,dj1,dj2,par)
%MAT
%    [M,B,G,W,DW,E] = MAT(Q1,J1,J2,DQ1,DJ1,DJ2,IN7)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    29-Apr-2020 15:14:26

J1 = par.J1; J2 = par.J2; J0 = par.J0;
al = par.al; g = par.g;
l = par.l; beta = par.beta; 
m0= par.m0; gama1= par.gama1; gama2= par.gama2;
k = par.k;

t2 = cos(j1);
t3 = cos(j2);
t4 = cos(q1);
t5 = sin(j1);
t6 = sin(j2);
t7 = sin(q1);
t8 = j1+j2;
t9 = j2+q1;
t10 = beta.^2;
t11 = dj1.^2;
t12 = dj2.^2;
t13 = dq1.^2;
t14 = gama2.*2.0;
t15 = j2.*2.0;
t16 = l.^2;
t17 = gama1+gama2+1.0;
t23 = -J1;
t25 = -al;
t27 = -q1;
t18 = beta.*t4;
t19 = cos(t8);
t20 = cos(t9);
t21 = beta.*t7;
t22 = sin(t8);
t24 = sin(t9);
t26 = -t15;
t30 = m0.*t16;
t35 = gama1+t14+2.0;
t36 = al+t27;
t38 = j1+t27;
t39 = m0.*t17;
t50 = t9+t25;
t28 = l.*t18;
t29 = l.*t21;
t33 = l.*t20;
t34 = l.*t24;
t37 = -t18;
t40 = gama2.*t30;
t43 = sin(t38);
t44 = -t24;
t45 = -t30;
t48 = cos(t36);
t49 = j1+t36;
t51 = cos(t38);
t53 = cos(t50);
t57 = gama2.*t12.*t22;
t58 = dj2.*dq1.*t14.*t22;
t59 = (gama1.*t30)./4.0;
t68 = (beta.*t2.*t30)./2.0;
t31 = t28.*2.0;
t32 = t29.*2.0;
t41 = -t28;
t46 = dj2.*t33;
t47 = dj2.*t34;
t52 = cos(t49);
t54 = -t34;
t55 = -t40;
t56 = beta.*t2.*t40;
t60 = t40./4.0;
t61 = dj1.*l.*t51;
t62 = dj1.*l.*t43;
t63 = l.*t51.*2.0;
t64 = l.*t43.*2.0;
t65 = -t59;
t66 = (gama2.*m0.*t33)./2.0;
t67 = (gama2.*m0.*t34)./2.0;
t69 = (beta.*t3.*t40)./2.0;
t74 = (t19.*t40)./2.0;
t76 = (gama1.*l.*m0.*t51)./2.0;
t77 = (gama1.*l.*m0.*t43)./2.0;
t82 = (g.*gama2.*l.*m0.*t53)./2.0;
t85 = t20+t37+t51;
t86 = t21+t43+t44;
t87 = (l.*m0.*t35.*t51)./2.0;
t88 = (l.*m0.*t35.*t43)./2.0;
t42 = -t31;
t70 = -t66;
t71 = g.*l.*m0.*t52;
t72 = -t69;
t75 = -t74;
t78 = -t76;
t79 = -t77;
t80 = t29+t64;
t83 = -t82;
t84 = t41+t63;
t91 = m0.*(t28-t63).*(-1.0./2.0);
t93 = (m0.*(t28-t63))./2.0;
t94 = t32+t54+t64;
t73 = gama2.*t71;
t81 = (gama1.*t71)./2.0;
t89 = (m0.*t80)./2.0;
t92 = t33+t42+t63;
t97 = (gama2.*m0.*t94)./2.0;
t99 = J2+t60+t72+t74;
t100 = t23+t45+t55+t56+t65+t68+t75;
t90 = -t89;
t95 = (gama2.*m0.*t92)./2.0;
t98 = -t97;
t96 = -t95;
t101 = t79+t90+t98;
t102 = t78+t93+t96;
M = reshape([t39,0.0,t101,t88,t67,0.0,t39,t102,t87,t70,t101,t102,J0+J1+J2+t30+t40.*(5.0./4.0)-t56.*2.0+t59+(t10.*t30)./4.0+t10.*t40+t19.*t40+beta.*t2.*t45+beta.*t3.*t55,t100,t99,t88,t87,t100,J1+t30+t40+t59,t75,t67,t70,t99,t75,J2+t60],[5,5]);
if nargout > 1
    B = [(l.*m0.*(t13.*t37+t11.*t51.*2.0+t13.*t51.*2.0-dj1.*dq1.*t51.*4.0-gama2.*t13.*t18.*2.0+gama2.*t12.*t20+gama2.*t13.*t20+gama1.*t11.*t51+gama1.*t13.*t51+t11.*t14.*t51+t13.*t14.*t51-dj1.*dq1.*gama1.*t51.*2.0-dj1.*dq1.*gama2.*t51.*4.0+dj2.*dq1.*t14.*t20))./2.0;l.*m0.*(t13.*t21+t11.*t43.*2.0+t13.*t43.*2.0-dj1.*dq1.*t43.*4.0+gama1.*t11.*t43+gama1.*t13.*t43+gama2.*t12.*t44+gama2.*t13.*t44+t13.*t14.*t21+t11.*t14.*t43+t13.*t14.*t43-dj2.*dq1.*gama2.*t24.*2.0-dj1.*dq1.*gama1.*t43.*2.0-dj1.*dq1.*gama2.*t43.*4.0).*(-1.0./2.0);t30.*(t57+beta.*t5.*t11-gama2.*t11.*t22+dj1.*dq1.*gama2.*t22.*2.0+dj2.*dq1.*gama2.*t22.*2.0+beta.*gama2.*t5.*t11.*2.0-beta.*gama2.*t6.*t12-beta.*dj1.*dq1.*t5.*2.0-beta.*dj1.*dq1.*gama2.*t5.*4.0-beta.*dj2.*dq1.*t6.*t14).*(-1.0./2.0);(t30.*(t57+t58-beta.*t5.*t13+gama2.*t13.*t22-beta.*gama2.*t5.*t13.*2.0))./2.0;(t40.*(t11.*t22+t13.*t22-dj1.*dq1.*t22.*2.0-beta.*t6.*t13))./2.0];
end
if nargout > 2
    G = [-g.*t39.*sin(al);g.*t39.*cos(al);-t71-t73-t81+t83+j1.*k+k.*q1+(beta.*g.*l.*m0.*t48)./2.0+beta.*g.*gama2.*l.*m0.*t48;t71+t73+t81+(k.*(j1.*4.0+q1.*2.0+t26))./2.0;t83-(k.*(j1.*2.0+t26))./2.0];
end
if nargout > 3
    W = reshape([1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,-l.*t86,-l.*t85,0.0,0.0,l.*t43,l.*t51,0.0,0.0,t34,-t33],[4,5]);
end
if nargout > 4
    dW = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t46-t61+dq1.*l.*t85,t47+t62-dq1.*l.*t86,0.0,0.0,t61-dq1.*l.*t51,-t62+dq1.*l.*t43,0.0,0.0,t46+dq1.*t33,t47+dq1.*t34],[4,5]);
end
if nargout > 5
    E = reshape([0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0],[5,2]);
end
